#include "DSPByROT.h"
#include "ROTFileSys.h"
#include "lowLevelSys.h"

#define POSSIBLE_STEPS                    10

typedef enum sysSteps
{
	GENERATE_SIG_PY =                     0x01,
	READ_SIG_FROM_TXT,                   // read values previousl generated by python random func
	READ_SIG_AS_INPUT,                   // let user input values for x[n]
	WRITE_SIG_TO_TXT,                    //only if read signal as input from user
	PY_READ_SIG_FROM_TXT,                // if read signal as input from user, make python read the signal from the .txt file
	COMPUTE_DFT_BY_DEF,                  // call DFT function to compute dft by definition
	COMPUTE_FFT_RADIX_2,                 // calculate spectrum by applying fft radix 2 algorithm
	WRITE_OUTPUT_SIG_TO_TXT,             // write the spectrum signal to .txt file
	PY_READ_OUTPUT_SIG,                  // make python read the output sig values from .txt file
	PLOT_SIGS                           // call python to plot imput and output signals
}sysSteps;

char path[] = "sigs.txt";               // define path for signals txt file

void generateSig(void);
void* callSigFileRead(void);

void* sysStateHandler[POSSIBLE_STEPS] = {
	generateSig,
	callSigFileRead(),
	readSigFromUser,

};

void* callSigFileRead(void)
{
	sigFileRead(path, Xout);
}
void sysStepsHandler(char inputType, char dftType)
{
	// handle the system steps;
};

void generateSig(void)
{
	// call python program to generate random input sig x[n]
};

